### ISSUE TITLE
Incorrect answer hint is... incorrect

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/thinkcspy#102]
Error reported in course thinkcspy on page 2DimensionalIterationImageProcessing by user marcusround marcusround@gmail.com
If you pick the first option you get an error message:

These are the values for the pixel at row 30, column 100. Get the values for row 100 and column 30 with p = img.getPixel(100, 30).

But the first option is exactly what you DO get when you use getPixel(100, 30). The question accepts as correct the answer you get when you use getPixel(30, 100). So to be honest I'm not sure which one is actually correct.

**Comment by bnmnetp** [comment]
The first parameter of getPixel is for the column and the second is for the row.  The book is correct.
