### ISSUE TITLE
Typo in Exercise turtle-8-4

### ISSUE THREAD

**Issue by cigas** [RunestoneInteractive/thinkcspy#103]
Section 4.7 - The range Function

turtle-8-4: Which range function call will produce the sequence 20, 15, 10, 5?

The explanation for the correct choice has a typo in the sequence: 25 should be 15.

✔️ Yes: If we take steps of -5, not worrying about the ending, we get 20, **25**, 10, 5, 0, .... The limit 3 is past the 5, so the range sequence stops with the 5.

**Comment by JaneDalenMiller** [comment]
fixed
