### ISSUE TITLE
Can't open the book

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/thinkcspy#107]
Error reported in course AlproD3 on page https://runestone.academy/runestone/static/pythonds/index.html by user fachry.arrasyid53@gmail.com fachry.arrasyid53@gmail.com
Hello sir, I have some problem in runstone, The book titled "Problem Solving with Algorithm and Data Structure using Python" can't be opened, the message "Hey there you appear to have wandered into pythonds But you are not registered for this course. Sending you to safety" will show if i want to open it, but i have already registered (that book can be opened before that day). Can you solve the problem ? 

thank you for your attention sir

**Comment by bnmnetp** [comment]
Yes the pop up is there to keep you from accidentally doing work in a course you are not registered for.  You are registered for AlproD3.  If you also want to use pythonds then you can register for that course too and use the Change Course feature to move back and forth.
