### ISSUE TITLE
Unfinished section

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/thinkcspy#108]
Error reported in course thinkcspy on page 12_model_view_controller by user shadowgritz nicholas.brewer90@gmail.com
The section on Model-View-Controller seems to be unfinished. There isn't any code showing how the Model-View-Controller setup works. 

In fact the entire chapter feels a bit undone and not well paced. The Whack-a-Mole game would be a good opportunity to teach more about tkinter if it were spread out over a few more pages rather than lumped together in one.

**Comment by bnmnetp** [comment]
thanks for your feedback
