### ISSUE TITLE
Mis-match in number of activities available on a page

### ISSUE THREAD

**Issue by dianeroux** [RunestoneInteractive/thinkcspy#110]
On page 1.2 "Algorithms", the message at the bottom of the page indicates there are 5 activities to be completed, but I only see 3 (2 quizzes, and "reading" the page).  See screenshot below.

There is also a problem on pages 2.2, 2.9, and 2.11. (I've only checked chapters 1 and 2 so far).

![runestone](https://user-images.githubusercontent.com/32103576/61095056-eb4acc80-a41f-11e9-822b-b8ac3ff2400d.PNG)

**Comment by bnmnetp** [comment]
Thanks for the report Diane.  I was pretty much expecting/hoping to see some reports like this.  I have long suspected that we had some cruft in our database, and some user generated questions that crept into places they should not have over the years.  This counter will help us pinpoint and remove/fix the old stuff.  

I’m on vacation for a week, but I’ll get on this when I get back.

**Comment by bnmnetp** [comment]
There were a few interesting twists to this, but I think I have them all sorted out now.  Please take a look and let me know if the numbers still seem wrong!

**Comment by cigas** [comment]
The textbook page shows 3 items on the count, but when I created an assignment, that count is still at 5. 

![image](https://user-images.githubusercontent.com/11619455/62334613-00020980-b48e-11e9-9f52-a641ec3fc35c.png)

**Comment by bnmnetp** [comment]
Thanks I will take a look at this.

**Comment by bnmnetp** [comment]
I just created a test course and added the Chapter as a reading assignment.  For me the activity count in Algorithms is 3.  When did you make this assignment?

**Comment by bnmnetp** [comment]
Nevermind...  The original number it shows when you select the subchapter is correct, but it was showing the wrong number after a page refresh.  I've fixed in on my dev server and will push the change today.

**Comment by bnmnetp** [comment]
It should be showing 3 now instead of 5.

**Comment by cigas** [comment]
That fixed it for me. I think all these changes also fixed issue

Reading assignments - some more inaccurate activity counts #698 in RunestoneComponents

so you can close that issue if you agree.

**Comment by bnmnetp** [comment]
Great. I'll keep this open until I hear back from @dianeroux that it fixed the counts for her as well.

Really glad to have a handle on this one!

**Comment by dianeroux** [comment]
Yes, it's working for me as well.  Thank you!  Diane


________________________________
