### ISSUE TITLE
Question is introduced before it has been taught.Q 14 on Page 6.13 Exerices

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/thinkcspy#121]
Error reported in course thinkcspy on page https://runestone.academy/runestone/books/published/thinkcspy/Functions/Exercises.html by user AbidRaza abid.raza.gp@gmail.com
Q.14. Approximation of Newton Algorithm. The program requires while and conditionals to confirm the number of time the loop will run  which will be introduced later in the book.Please confirm

**Comment by bnmnetp** [comment]
This can be written as a fixed number of iterations as practice for the accumulator pattern.  Later students can improve with while loops
