### ISSUE TITLE
"Ch 7.4. Conditional Execution: Binary Selection" has an unrelated Lab from "Ch 20.5"

### ISSUE THREAD

**Issue by milant** [RunestoneInteractive/thinkcspy#123]
In section **7.4. Conditional Execution: Binary Selection**, there is an unrelated Lab from section **20.5 Approximating the Value of Pi**.

> **Lab**
> Approximating Pi with Simulation In this guided lab exercise we will work through a problem solving exercise related to approximating the value of pi using random numbers.

This needs to be corrected or removed.

**Comment by bnmnetp** [comment]
what is it that you find to be problematic about the link to this lab?  This is an appropriate project that will allow students to practice with selection.
