### ISSUE TITLE
Audio Tour Broken

### ISSUE THREAD

**Issue by sschaub** [RunestoneInteractive/thinkcspy#128]
The audio tour on this page is broken:

https://runestone.academy/runestone/books/published/thinkcspy/PythonTurtle/OurFirstTurtleProgram.html

The audio resource URL's point to media.interactivepython.org, but the URL's appear to be broken.

**Comment by bnmnetp** [comment]
missing files recovered, problem solved.

**Comment by sschaub** [comment]
The audio tour is still not working for me. The browser console reports certificate errors for the audio links.

**Comment by bnmnetp** [comment]
Its working fine for me. can you show me the error message?  What browser and version are you using?

**Comment by bnmnetp** [comment]
I hate that chrome just decides to change an http to an https and if the site hasn't set up a cert it just fails.  I get that security is good, but at least Chrome should fall back to an http site and give you a warning.

**Comment by bnmnetp** [comment]
Should be fine now.... I think I have created certificates for all of the domains.

**Comment by sschaub** [comment]
Works for me! 

It is unfortunate that Chrome has taken an increasingly hostile stance towards unencrypted http.
