### ISSUE TITLE
Can't complete all activities on 2.4 and 2.9

### ISSUE THREAD

**Issue by cigas** [RunestoneInteractive/thinkcspy#131]
The pages for ch 2.4 and 2.9 don't seem to count viewing the video, so a student can never complete all seven activities on the page. I've tried this using Firefox 79 on Windows. Ch 2.6 worked as expected. 
![Ch2 4](https://user-images.githubusercontent.com/11619455/89741961-528be380-da5b-11ea-9880-580e91ffbfe8.png)
![ch2 9](https://user-images.githubusercontent.com/11619455/89741964-5881c480-da5b-11ea-9dc1-b231b04b9c75.PNG)

**Comment by bnmnetp** [comment]
What book?

**Comment by bnmnetp** [comment]
Hmm, I just checked and I'm getting a correct count in 2.4 and 2.9 in Safari.  Are you seeing any error messages in the Firefox developer console?

**Comment by cigas** [comment]
I ran under Chrome, and that fixed all the counts after I redid all the activities. 

Here are the 3 errors from Firefox:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://googleads.g.doubleclick.net/pagead/id. (Reason: CORS request did not succeed).

Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). 3 utils.js:35:9

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://googleads.g.doubleclick.net/pagead/id. (Reason: CORS request did not succeed).

I do have ad blocking and privacy plugins, but 

- 2.6 worked for me. 
- This behavior was reported to me by another instructor who does not use plugins, and I duplicated it

Here are the errors from 2.6, which worked:

Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). 2 utils.js:35:9

**Failed to execute ‘postMessage’ on ‘DOMWindow’: The target origin provided (‘https://www.youtube.com’) does not match the recipient window’s origin (‘https://runestone.academy’). StatementsandExpressions.html**

Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). utils.js:35:9

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://googleads.g.doubleclick.net/pagead/id. (Reason: CORS request did not succeed).

**Comment by bnmnetp** [comment]
I'll have to take a closer look when I'm back from a mini-vacation, later this week.

Are you logged in?  I'm concerned about that googleads url that I'm seeing.  That should not be there, unless it is related to a youtube video.

**Comment by cigas** [comment]
I was logged in to Runestone, but may not have been logged in to Google. Just a thought.

**Comment by bnmnetp** [comment]
Have you seen any more problems like this recently?

**Comment by cigas** [comment]
No I haven't. Students in my fall section were able to get 100% on these problems that I mentioned, so it looks like it's fixed.
