### ISSUE TITLE
Messed-up questions

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/thinkcspy#133]
Error reported in course Century-Reddish-Programming on page https://runestone.academy/runestone/assignments/doAssignment?assignment_id=47205 by user 4009322 4009322@sd25.me
A lot of the questions are worded incorrectly:
"In Python a module you mama cause?"
"In Python a module stupid:"
(should be "In Python a module is:")
"True / False: All standard Python modules will work in dumb activecode."
(should be "True / False: All standard Python modules will work in activecode."

**Comment by bnmnetp** [comment]
These are instructor contributed questions.  Your instructor should not be assigning you bad questions like this.
