### ISSUE TITLE
Wrong meaning

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/thinkcspy#18]
Error reported in course thinkcspy on page ValuesandDataTypes by user vader vadermania@gmail.com
"When we show the value of a string using the print function, such as in the third example above, the quotes are no longer present." 
In fact, they are present. When removed, the interpreter thinks that the two words are two values. 
I think there is a mistake in the sentences' "semantics", :).

**Comment by bnmnetp** [comment]
clarified
