### ISSUE TITLE
Logical Opposites Table typo in thinkcspy

### ISSUE THREAD

**Issue by mrericreed** [RunestoneInteractive/thinkcspy#182]
**What Course are you in**
thinkcspy

**What Page were you on**
https://runestone.academy/runestone/books/published/thinkcspy/Selection/Logicaloperators.html#logical-opposites

**What is your username**
EricReed

**Describe the bug**
Opposite operator for "greater than or equal to" is listed as <=.  Should be <

**Comment by bnmnetp** [comment]
@qasema Can you fix this please.

**Comment by qasema** [comment]
Yes, I will work on it today
