### ISSUE TITLE
Truth table typo in thinkcspy

### ISSUE THREAD

**Issue by mrericreed** [RunestoneInteractive/thinkcspy#184]
**What Course are you in**
thinkcspy

**What Page were you on**
Section 7.2
https://runestone.academy/runestone/books/published/thinkcspy/Selection/Logicaloperators.html

**What is your username**
EricReed

**Describe the bug**
The truth table just above the Google Doodle lists (F OR T) as F.

Thank you!

**Comment by bnmnetp** [comment]
@qasema here is another little typo.

**Comment by qasema** [comment]
@bnmnetp done
