### ISSUE TITLE
Can't run Activity: 19.3.1 ActiveCoce

### ISSUE THREAD

**Issue by cigas** [RunestoneInteractive/thinkcspy#187]
**What Course are you in**
CS152HOSP2021

**What Page were you on**
https://runestone.academy/runestone/books/published/thinkcspy/Inheritance/03-Extending.html

**What is your username**
cigas

**Describe the bug**
Clicking on Save & Run generates the  error 
ExternalError: InternalError: too much recursion on line 20
(see the image)
The code works fine when I copy it and run it locally with my own python environment.
![image](https://user-images.githubusercontent.com/11619455/128094126-432abe05-f170-407e-acb2-5f45a33803cf.png)

**Comment by bnmnetp** [comment]
Looks like a bug in https://github.com/skulpt/skulpt that is now fixed.  I have not done my usual summer sync with the main branch of skulpt yet....  I guess this gives me some motivation to do that.

**Comment by bnmnetp** [comment]
Yes, it was a bug in skulpt, but the team skulpt has fixed it.  I'm testing that fix and a bunch of other great updates they have been working.  Hopefully will be live this weekend.

**Comment by cigas** [comment]
Looks good. Thanks.
