### ISSUE TITLE
Not introduced what is a variable

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/thinkcspy#19]
Error reported in course thinkcspy on page ValuesandDataTypes by user vader vadermania@gmail.com
You used the variable "message" but did not explain that this is a variable. It is quite easy to induct this - almost subconscious - but some people might need an explanation. 

User: vader

**Comment by bnmnetp** [comment]
Better to remove that as its the only example in this section that assigns to a variable.  They are defined and covered in 2.4.

Fixed.
