### ISSUE TITLE
Result typo?

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/thinkcspy#21]
Error reported in course thinkcspy on page Exercises by user solid ciaopharma@gmail.com
The below exercise has a result of 344.  The sum of squares should be 365. 

    Result	Actual Value	Expected Value	Notes
    Pass	29	29	Tested sum_of_squares on input [2,3,4]
    Pass	2	2	Tested sum_of_squares on input [0,1,-1]
    Fail	365	344	Tested sum_of_squares on input [5,12,14]

    You passed: 66.6666666667% of the tests

    (ex_7_11)

**Comment by bnmnetp** [comment]
fixed
