### ISSUE TITLE
Text Formatting Issues- Pretext Version

### ISSUE THREAD

**Issue by dsanders12** [RunestoneInteractive/thinkcspy#219]
When looking at tip and caution statements within the pretext version, they are indistinguishable for normal text.
ReStructured Text:
![image](https://user-images.githubusercontent.com/46610441/176708400-532eca76-d296-4400-bd32-713b43665c4a.png)

PreText:
![image](https://user-images.githubusercontent.com/46610441/176708617-c103cd28-ded5-4132-8850-45281df8f5e4.png)

ReStructured Text:
![image](https://user-images.githubusercontent.com/46610441/176708799-ac20dc90-3b27-4046-b67f-40b3f17b2785.png)

PreText:
![image](https://user-images.githubusercontent.com/46610441/176710132-2397da87-f2a7-4e4a-8575-cca579e89cd3.png)

**Comment by dsanders12** [comment]
@bnmnetp currently working on this issue, it seems that the root issue is that the tip and caution tags in PreText do not seem to work as intended, when I view them in my local book build.

**Comment by bnmnetp** [comment]
A few things 

1. Neither tip nor caution are PreTeXt tags.  These are tags that the converter program didn't know about and just passed them through. - its good for me to know about them so I can make the converter smarter for future conversions.
2. PreTeXt is very well documented.  Start at pretextbook.org  - the sample book has lots of examples and the guide is a more formal documentation of ALL of the tags in pretext.

For example the `<tip>` should maybe become a `<note>` and the `<caution>` should become a `<warning>`. Don't worry if they don't look exactly like the Runestone we will adjust the look of the book with CSS over time.

PreTeXt and restructureText have very very different underlying philosophies.   
* RST doesn't care about the structure of the document much at all (beyond section, subsection, etc), but gives you some tools to change how things are formatted.  
* PreTeXt wants the book to be highly structured into units that make sense.  With the structure in place we can use other tools to make those units look like we want. 

So, by default here is what it looks like if you change the caution to warning.  I may not be super excited by the look of that, its OK for now.  We can fix the styling later.

<img width="683" alt="Screen Shot 2022-06-30 at 10 42 03 AM" src="https://user-images.githubusercontent.com/51115/176719710-66efb70d-724b-41a4-a571-007e60bfffb3.png">


This is good, it is going to take some conversation to figure out how to do this, and what things the converter didn't convert correctly or at all it will be a collaborative effort.
