### ISSUE TITLE
Incorrect link

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/thinkcspy#22]
Error reported in course usafa_cs210_2016 on page StringMethods by user waynebrown wayne.Brown@usafa.edu
The link to the Python documentation for strings goes to the wrong place in the documentation. The exact text is: "You can also consult the Python documentation for strings."

Save & RunLoad HistoryShow CodeLens

 The current link is: https://docs.python.org/3/library/stdtypes.html#index-21

The link should be: https://docs.python.org/3/library/stdtypes.html#text-sequence-type-str
    or https://docs.python.org/3/library/stdtypes.html#string-methods

Thanks

**Comment by bnmnetp** [comment]
fixed
