### ISSUE TITLE
Checkpoints 2.8.2 & 2.8.3 not rendered-- PreTeXt version

### ISSUE THREAD

**Issue by dsanders12** [RunestoneInteractive/thinkcspy#235]
The clickable area questions do not appear in Chapter 2.8
![image](https://user-images.githubusercontent.com/46610441/176750275-e8d1c272-44b0-4936-94a0-99132745c1ac.png)

**Comment by dsanders12** [comment]
@bnmnetp currently working on issue.

**Comment by bnmnetp** [comment]
Those are not multiple choice questions those are clickable area questions.

The easiest thing to do would be to look at the source in rst and write them in PreTeXt.    We have support for them in PreTeXt but it got added after I had done this conversion.  I think there are only a couple of them (these may be the only two) to do.
