### ISSUE TITLE
broken external link (404) - updated link provided

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/thinkcspy#26]
Error reported in course thinkcspy on page OurFirstTurtleProgram by user Sriap 39087781@opayq.com
link to colour names leads to 404 page.
working link is: http://www.w3schools.com/colors/colors_names.asp

"Hint: you can find a list of permitted color names at http://www.w3schools.com/html/html_colornames.asp. "

**Comment by bnmnetp** [comment]
fixed
