### ISSUE TITLE
activecode button names

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/thinkcspy#31]
Error reported in course thinkcspy on page SpecialWaystoExecutePythoninthisBook by user drjwsimmons simmonsj@rhodes.edu
The text says that activecode has Save, Run, and Load buttons, but it actually has Save&Run, Load History, and Show Codelens buttons.  The text appears to describe an older version of activecode.

**Comment by bnmnetp** [comment]
fixed
