### ISSUE TITLE
Setting turtle up() is in the wrong location.

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/thinkcspy#32]
Error reported in course thinkcspy on page montepi by user apa apa@moogzy.net
Under the throwing darts section.

fred.up() is currently initialized right after the instantiation of turtle.Turtle().

However this results in the turtle still leaving a line. What needs to happen is fred.up() called after the window has been instantiated.

I've tested the above and it no longer leaves a line.

**Comment by bnmnetp** [comment]
@gardhi01 can you verify that this is still a problem, and if so change the example so the turtle does not leave a line.
