### ISSUE TITLE
9.11 

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/thinkcspy#33]
Error reported in course thinkcspy on page http://interactivepython.org/runestone/static/thinkcspy/Strings/TraversalandtheforLoopByIndex.html by user Jimpat jimpatfitzpatrick@gmail.com
The links to all the previous and post pages (that I have tried) take you to the correct  page. 
This one goes to
 {"log": true}[{"redirect": "/runestone/default/user/login"}]
Your course is fantastic and a huge help. Many thanks
Kind regards
Thomas Fitzpatrick
027 21 709 0488

**Comment by bnmnetp** [comment]
Seems fine now.
