### ISSUE TITLE
Issue #34 closed, but not resolved

### ISSUE THREAD

**Issue by iainism** [RunestoneInteractive/thinkcspy#41]
[Issue #34](https://github.com/RunestoneInteractive/thinkcspy/issues/34) appears to have been closed, despite the problems stated in the original report still being present in [Section 14.32](http://interactivepython.org/runestone/static/thinkcspy/GUIandEventDrivenProgramming/11_gui_program_example.html):

- Embedded graphics (e.g. "GUIandEventDrivenProgramming/Figures/Whack_a_mole_design.png") are not being shown, and
- The page text contains _multiple_ dead links to source code (e.g. "[whack_a_mole_v1.py](http://interactivepython.org/runestone/static/thinkcspy/GUIandEventDrivenProgramming/Programs/whack_a_mole_v1.py)")

**Comment by bnmnetp** [comment]
A fix for this has been committed. It's just not deployed yet. Please be patient.

**Comment by bnmnetp** [comment]
fix is now live.

**Comment by iainism** [comment]
The embedded graphic is still missing...
