### ISSUE TITLE
activecode exercises need to be updated with text in the content

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/thinkcspy#49]
Now that more people are using the interface to build assignments, it is very problematic that the exercises were written with the question outside the directive.  This means that when you add an exercise to an assignment all you get is the codemirror box and any sample code.  But you can't see what you are supposed to do!  The solution is simply to move the explanation inside the directive.
```
.. actex:: foo
   :options heree:

   The question text should go here followed by 4 ~
   ~~~~
   sample code if any
   ====
   hidden code
```

- [x] GeneralIntro
- [x] SimplePythonData
- [x] Debugging
- [x] PythonTurtle
- [x] PythonModules
- [x] Functions
- [x] Selection
- [x] MoreAboutIteration
- [x] Strings
- [x] Lists
- [x] Files
- [x] Dictionaries
- [x] Exceptions
- [x] GUIandEventDrivenProgramming
- [x] IntroRecursion
- [x] ClassesBasics
- [x] ClassesDiggingDeeper
- [x] Labs

**Comment by conzty01** [comment]
Do you want me to update the directive itself too, or simply just the entries on ActiveCode examples on each of these pages?

**Comment by bnmnetp** [comment]
The directive is already updated.  We just need to update the source in the books.

**Comment by bnmnetp** [comment]
I'll work from the bottom of the list toward the top.

**Comment by conzty01** [comment]
Are we just changing the `actex` or are we also changing the `activecode` directives?

**Comment by bnmnetp** [comment]
Its not 100% consistent, some of them **may** be activecode

**Comment by conzty01** [comment]
I can't seem to check the boxes above, but so far I've gone up through the Functions chapter.

**Comment by bnmnetp** [comment]
Excellent, make a PR and we can cross this one off.
