### ISSUE TITLE
ex_5_8

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/thinkcspy#61]
This problem seems to have an indentation weirdness.

![image](https://user-images.githubusercontent.com/28868409/30303930-afd2e926-971f-11e7-8c2b-8e8e2fba0ef4.png)

Looking at the Edit source page, there are only 3 spaces in the yellow area and 4 spaces in the pink.

![image](https://user-images.githubusercontent.com/28868409/30303984-fd71010e-971f-11e7-92e7-61b64058b185.png)

**Comment by bnmnetp** [comment]
Drat, indentation problems.  Easy enough to fix.

**Comment by psmaker** [comment]
Tried ex_5_8 and now get this weird message.  Looked at the ex_5_8 source and it looks OK. Do I need to rebuild?

![image](https://user-images.githubusercontent.com/28868409/30391172-57082244-986d-11e7-8fd7-094788020113.png)

**Comment by bnmnetp** [comment]
Yes, you need to rebuild.

**Comment by psmaker** [comment]
I rebuilt. It still has an issue.

I think maybe it is using the older .actex with a unittest.

**Comment by bnmnetp** [comment]
I was off by one in my fix -- even though I swear I tested locally before pushing.

Anyway you will need to do another rebuild.  I have done so and verified that it now works (after clearing cache) on my course on academy.

**Comment by psmaker** [comment]
Yup - all fixed!  Thanks!
