### ISSUE TITLE
SyntaxError: bad input on line - Exercises: ex_5_7, ex_5_8, ex_5_13 and ex_5_14

### ISSUE THREAD

**Issue by EricGT** [RunestoneInteractive/thinkcspy#62]
SyntaxError: bad input on line ???
For section: 6 - Functions
Exercises: ex_5_7, ex_5_8, ex_5_13 and ex_5_14 

At present I do not know the exact root cause. 

The commonality of these four examples can be seen by looking at the [rst](https://github.com/RunestoneInteractive/thinkcspy/blob/master/_sources/Functions/thinkcspyExercises.rst) file for the functions examples.

These four all have 

```
====
from unittest.gui import TestCaseGui
```

Once the error occurs for one of these examples I have found no way to resolve it. Clearing the box and inserting new code does not work and changing browsers does not resolve the problem.

I suspect this has something to do with using copy and paste as I was able to successfully complete exercise ex_6_6 without any problems.

However for exercise ex_6_3 I noticed that the indentation for my code started in column 2 instead of column 1 and by adjusting the start of the code I now receive error:

```
IndentationError: unindent does not match any outer indentation level on line 15
 from unittest.gui import TestCaseGui

 ^
```
The code visible on the screen ends on line **13** and the error is on line **15**.

Versions
---

My versions:
Microsoft Windows 10.0.15063
Microsoft Edge 40.15063.0.0
Microsoft EdgeHTML 15.15063

Course name (which is a copy of thinkcspy) : solebury_2017_fall

Similar exercises
----

While I have not checked the following examples, they also have the same pattern in the rst file. 

recursion
ex_rec_1
ex_rec_2

lists
ex_7_11
ex_9_6
ex_9_7
ex_9_8
ex_9_10
ex_9_13

moreiter
ex_7_9

selection
ex_6_3
ex_6_6
ex_6_7
ex_6_8
ex_6_9
ex_6_10
ex_6_11
ex_6_12

strings
ex_7_10
ex_8_5
ex_8_6
ex_8_7
ex_8_8
ex_8_9
ex_8_10
ex_8_11
ex_8_19

**Comment by bnmnetp** [comment]
This has been reported a few times and is fixed.  You need to rebuild your course.   There was a small indentation mismatch that has been corrected in the source.  I hope I caught them all, but thanks for the list.

**Comment by EricGT** [comment]
Using the instructors page rebuilt the course and verified exercises ex_5_7, ex_5_8, ex_5_13 and ex_5_14 are now working as expected.

Thanks.

Closing issue.
