### ISSUE TITLE
indent problem in Selection chapter

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/thinkcspy#63]
Found another problem with the indentation in the Exercises of the Selection unit

![image](https://user-images.githubusercontent.com/28868409/30679944-aec2f150-9e51-11e7-8631-a86b347cbe97.png)

**Comment by bnmnetp** [comment]
Fix is deployed to the site now.  Rebuild should fix your course.

**Comment by psmaker** [comment]
Fixed - thanks - I just just minutes away from filing a PR for this one... oh well...

**Comment by bnmnetp** [comment]
@EricGT beat you to it. You can get the next one 😄
