### ISSUE TITLE
Little exercise issues

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/thinkcspy#66]
Error reported in course CSC2-140 on page Variablesandparametersarelocal by user tdelaubenfels tdelaubenfels@cornellcollege.edu
func 3_1 doesn't display anything other than a green stripe after answer.
The answer to func 4_1 doesn't match the source code (initialize isn't in the loop)

**Comment by christsona** [comment]
Hello, my name is Aaron, a Berea College student, and I'm working on this issue.

**Comment by pearcej** [comment]
@bnmnetp I believe this issue was resolved by pull request #124
