### ISSUE TITLE
Answer for turtle6.6

### ISSUE THREAD

**Issue by hemangsk** [RunestoneInteractive/thinkcspy#7]
Greetings :smile: 

Thanks for creating such an amazing resource.

The answer for turtle 6.6 seems incorrect.  The present answer is 'c'. 

![screen shot 2016-06-07 at 12 34 52 pm](https://cloud.githubusercontent.com/assets/13018570/15848791/931bfdec-2cac-11e6-9a43-361262d9a7eb.png)
 
 Option 'a' seems the correct one as the turtle is drawing the complete square and in a single color only.

**Comment by bnmnetp** [comment]
The question asks you what each *iteration* of the loop does.  It does not ask you what happens after all iterations.

You are not the first person to think this is a bug. 😄
