### ISSUE TITLE
Lesson 14.31: Missing image files

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/thinkcspy#73]
Error reported in course thinkcspy on page https://runestone.academy/runestone/static/thinkcspy/GUIandEventDrivenProgramming/11_gui_program_example.html by user jimla jimglarsen@icloud.com
The examples in Lesson 14.31 cannot be run because the image files mole.png and mole_cover.png are not available. Note that tkinter version 8.6 is required to import png files. Version 8.5 can import only gif files. Thanks for creating this course!

Jim

**Comment by BinoyThomas1108** [comment]
Hi Jim,
I had the same problem as you. I searched the net, found an image, which I morphed into the 2 required files. Hope they help. The links are given below:

![Mole](https://user-images.githubusercontent.com/31699720/70203912-95ffb680-1744-11ea-8922-95b592c0c411.png)
![Mole_Cover](https://user-images.githubusercontent.com/31699720/70203913-96984d00-1744-11ea-9bd8-7285762556ee.png)

**Comment by bnmnetp** [comment]
Thanks!  Fix will be live this weekend.
