### ISSUE TITLE
Active Code Window for Ch 17 Exercises are from Ch 16 Exercises

### ISSUE THREAD

**Issue by psmaker** [RunestoneInteractive/thinkcspy#80]
Some of the Ch 17 Exercises seem to fetch the same code from Ch 16 Exercises.

For example, here is a Ch 16 exercise.
![image](https://user-images.githubusercontent.com/28868409/35745563-8acd33b2-07f8-11e8-91ca-8f6c340d8e42.png)

And here is the same code in a Ch 17 exercise.
![image](https://user-images.githubusercontent.com/28868409/35745606-b134d898-07f8-11e8-9c19-06271db1dbc7.png)

They both seem to use ``classes_q3``.

There are other overlapping exercises - ``classes_q5`` and ``classes_q6`` in Chapter 17 as well.

**Comment by bnmnetp** [comment]
The commented code is the same but the top is different. Are you seeing this as part of an assignment or on different exercises pages. If the latter it’s just a copy and paste issue. If the former it’s an I’d issue.

**Comment by psmaker** [comment]
I made this example shown above where I typed the comment into the Active Code window in the Ch 16 Exercises page. Then, when I ``Load History`` on the Ch 17 Exercise page, the exact same code popped up when it was never "Saved & Run". The top is different because they are from different exercises in the ThinkLikeCSPy book.

So, I think it is an id issue where ``classes_q3`` is being used for both of the Ch 16 and 17 Exercises.

**Comment by bnmnetp** [comment]
Ok. Thanks for clarifying. We need to fix the ids and then you will need to rebuild.  I can’t do that on my phone.  But I’ll let you know.

**Comment by psmaker** [comment]
In the .rst code...

 thinkcspy/_sources/ClassesDiggingDeeper/Exercises.rst 

![image](https://user-images.githubusercontent.com/28868409/35753622-5372e174-0815-11e8-96b2-b2392c80bbbe.png)

and in  thinkcspy/_sources/ClassesBasics/Exercises.rst 

![image](https://user-images.githubusercontent.com/28868409/35753671-7fa6caee-0815-11e8-93c9-008f0ddd7225.png)

I'm guessing that one just needs to change one of them to a different name so they don't overlap?

**Comment by bnmnetp** [comment]
Yep. PRs welcome!

**Comment by psmaker** [comment]
OK! Done! Hope is is OK...

**Comment by psmaker** [comment]
I tried re-building LHSIntroCS_2017 with this fix and it still seems to have the issue. Is the change in the Runestone site?

**Comment by bnmnetp** [comment]
I had not pushed the change because I wanted to make sure it didn't cause any funny problems.  I tested it on my dev build this morning, pushed it to the site just now.

Let me know if this doesn't fix it. You may need to drop and re-add those questions to your assignment. -- Or you may see duplicates from the assignment builder - if so let me know.

**Comment by psmaker** [comment]
OK thanks! We just started Ch 17, and since some classes already started doing it, I don't want to rebuild now and we'll just deal with the bug for this year.  I'll close this issue.
