### ISSUE TITLE
Instant time limit error

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/thinkcspy#87]
Error reported in course thinkcspy on page SentinelValuesAndValidation by user azt3k tonatiuh.cuauhtemoc@gmail.com
Hello,

I'm working through the def checkout() function exercise, and every time I run it, it tells me that the run time has exceeded the time limit allowed right after I submit the user input. I'm wondering if this is either: 1) Part of the problem I'm being tasked with solving, or 2) A bug somewhere in the activecode field? Any and all help will be very much appreciated!

**Comment by bnmnetp** [comment]
fixed
