### ISSUE TITLE
chapter 3.6 exercises missing

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/thinkcspy#90]
Error reported in course thinkcspy on page Exercises by user PancakeDave13 dakawa.kawa@gmail.com
chapter 3.6 exercises missing

**Comment by bnmnetp** [comment]
Not missing, there just are no exercises for the debugging chapter.  We should add the standard this page intentionally blank disclaimer.

**Comment by cbondurant** [comment]
Is this issue resolved? I looked at the chapter in question and it has the blank disclaimer on it already.

**Comment by bnmnetp** [comment]
Yep... closing.  Thanks
