### ISSUE TITLE
error in func_4_1 or think_cspy

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/thinkcspy#93]
Error reported in course cs_python on page TheAccumulatorPattern by user normprokup norm@college-prep.org
Func_4_1 seems to be written as if the line "runningtotal = 0"  was inside the loop, but it's not.  P. S. I love this site.

**Comment by bnmnetp** [comment]
But the question asks you what happens if it was written with the running total initialized to 0 inside the loop.
