### ISSUE TITLE
2.8. Input

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/thinkcspy#97]
Error reported in course thinkcspy on page https://runestone.academy/runestone/static/thinkcspy/SimplePythonData/Input.html by user rbchettri1 rbchettri@gmail.com
The last exercise says there are two objects of the <type 'str'> but I believe there is only one and for that reason the last exercise cannot be completed.

**Comment by bnmnetp** [comment]
There are two places in the code where the string variable is used.  You need to click on them both.
