### ISSUE TITLE
Pixellated Videos

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/thinkcspy#98]
Error reported in course thinkcspy on page TheforLoop by user tapariayogesh tapariayogesh@gmail.com
The videos are too pixellated to be able to read anything on the screencast videos.

**Comment by ConceptaNjolima** [comment]
I did some investigation and the video is pixellated on YouTube too. I think the only solution would be redoing the video because the pixellation has nothing to do with the Runestone book.
